// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Electron = require("electron");

function windowConfigToJs(param) {
  return {
          width: param[/* width */0],
          height: param[/* height */1],
          frame: param[/* frame */2],
          titleBarStyle: param[/* titleBarStyle */3]
        };
}

function windowConfigFromJs(param) {
  return /* record */[
          /* width */param.width,
          /* height */param.height,
          /* frame */param.frame,
          /* titleBarStyle */param.titleBarStyle
        ];
}

function make(options) {
  return new Electron.BrowserWindow(windowConfigToJs(options));
}

exports.windowConfigToJs = windowConfigToJs;
exports.windowConfigFromJs = windowConfigFromJs;
exports.make = make;
/* electron Not a pure module */
