// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json$BsElectron = require("./Json.bs.js");

function MakeBrowserWindow() {
  var sendWithArg = function (t, arg) {
    t.webContents.send("message", JSON.stringify(Json$BsElectron.toValidJson(arg)));
    return /* () */0;
  };
  var getVisibility = function (t) {
    var match = t.isVisible();
    if (match) {
      return /* Showing */-922362907;
    } else {
      return /* Hidden */19559306;
    }
  };
  return /* module */[
          /* sendWithArg */sendWithArg,
          /* getVisibility */getVisibility
        ];
}

exports.MakeBrowserWindow = MakeBrowserWindow;
/* No side effect */
