// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function getVisibility(t) {
  var match = t.isVisible();
  if (match) {
    return /* Showing */-922362907;
  } else {
    return /* Hidden */19559306;
  }
}

exports.getVisibility = getVisibility;
/* No side effect */
