// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Electron = require("electron");
var Json$BsElectron = require("./Json.bs.js");

function MakeIpcMain(T) {
  var on = function (cb) {
    Electron.ipcMain.on(T[/* message */0], (function ($$event, arg) {
            return cb($$event, Json$BsElectron.fromValidJson(JSON.parse(arg)));
          }));
    return /* () */0;
  };
  var partial_arg = T[/* message */0];
  var removeListener = function (param) {
    Electron.ipcMain.removeListener(partial_arg, param);
    return /* () */0;
  };
  return /* module */[
          /* on */on,
          /* removeListener */removeListener
        ];
}

exports.MakeIpcMain = MakeIpcMain;
/* electron Not a pure module */
