// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Electron = require("electron");
var Json$BsElectron = require("./Json.bs.js");

function MakeIpcRenderer() {
  var sendWithArg = function (arg) {
    Electron.ipcRenderer.send("message", JSON.stringify(Json$BsElectron.toValidJson(arg)));
    return /* () */0;
  };
  return /* module */[/* sendWithArg */sendWithArg];
}

function IpcMain() {
  var sendWithArg = function (arg) {
    Electron.ipcRenderer.send("message", JSON.stringify(Json$BsElectron.toValidJson(arg)));
    return /* () */0;
  };
  return /* module */[/* sendWithArg */sendWithArg];
}

exports.MakeIpcRenderer = MakeIpcRenderer;
exports.IpcMain = IpcMain;
/* electron Not a pure module */
