// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json$BsElectron = require("./Json.bs.js");
var Window$BsElectron = require("./Window.bs.js");

function MakeIpcRenderer(T) {
  var on = function (cb) {
    Window$BsElectron.electron.ipcRenderer.on(T[/* message */0], (function ($$event, arg) {
            return cb($$event, Json$BsElectron.fromValidJson(JSON.parse(arg)));
          }));
    return /* () */0;
  };
  var partial_arg = T[/* message */0];
  var removeListener = function (param) {
    Window$BsElectron.electron.ipcRenderer.removeListener(partial_arg, param);
    return /* () */0;
  };
  var send = function (arg) {
    Window$BsElectron.electron.ipcRenderer.send(T[/* message */0], JSON.stringify(Json$BsElectron.toValidJson(arg)));
    return /* () */0;
  };
  return /* module */[
          /* on */on,
          /* removeListener */removeListener,
          /* send */send
        ];
}

exports.MakeIpcRenderer = MakeIpcRenderer;
/* Window-BsElectron Not a pure module */
