// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function MakeWindowRequire(T) {
  var make = function () {
    return window.require(T[/* moduleName */0]);
  };
  return /* module */[/* make */make];
}

var moduleName = "electron";

function make() {
  return window.require(moduleName);
}

var Electron = /* module */[/* make */make];

var electron = window.require(moduleName);

exports.MakeWindowRequire = MakeWindowRequire;
exports.Electron = Electron;
exports.electron = electron;
/* electron Not a pure module */
