// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function MakeWindowRequire() {
  var partial_arg = window;
  var $$require = function (param) {
    return partial_arg.require(param);
  };
  return /* module */[/* require */$$require];
}

var partial_arg = window;

function $$require(param) {
  return partial_arg.require(param);
}

var Electron = /* module */[/* require */$$require];

var electron = Curry._1($$require, "electron");

exports.MakeWindowRequire = MakeWindowRequire;
exports.Electron = Electron;
exports.electron = electron;
/* partial_arg Not a pure module */
